source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do

  gem 'fabrication'
  gem "database_cleaner"

  gem "rspec-rails"
  

  gem 'mongoid-rspec'
  gem 'validation_matcher'
  gem 'json_spec'

  gem 'pry'
  gem 'pry-nav'

  gem 'rest-client'

  gem 'timecop'

  gem 'spork'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'guard-spork'
  gem 'rb-fsevent'
  gem 'terminal-notifier-guard', :require => false
end

group :test do
  gem 'vcr'
  gem 'webmock'
end

# Users Login
gem 'koala'
gem 'devise'
gem 'validates_email_format_of'

# API Rest
gem 'versionist'

# Database
gem 'mongoid', '~> 3.0.2'
gem 'sqlite3'

# Json
gem 'rabl'
gem 'oj'

# Pagination
gem 'kaminari'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
